name: CI
on: [push, pull_request]
jobs:
  vint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Lint with Vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Lint with Vint
        run: |
          python -m pip install vim-vint
          vint .
  vimlint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Lint with vimlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint with vimlint
        run: |
          git clone https://github.com/syngan/vim-vimlint $HOME/vim-vimlint
          git clone https://github.com/vim-jp/vim-vimlparser $HOME/vim-vimlparser
          $HOME/vim-vimlint/bin/vimlint.sh -u -l $HOME/vim-vimlint -p $HOME/vim-vimlparser -e EVL102.l:_=1 -e EVL103=1 .
